[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
coverage = "^5.5"
codecov = "^2.1.12"
pytest-cov = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"